### ISSUE TITLE
Official repos have moved to Packagecloud

### ISSUE THREAD

**Issue by gozer** [maxchk/puppet-varnish#146]
http://repo.varnish-cache.org/ doesn't exist anymore, unfortunately.

From: http://varnish-cache.org/releases/

Deb and RPM repositories now at Packagecloud
The official packages for Debian, Ubuntu, CentOS and Red Hat are now located in repositories at Packagecloud.io. Users of repo.varnish-cache.org repositories will have to change their hosts over to the new repository configuration. For details see the below sections for the distribution in question.

**Comment by tobixen** [comment]
I'm still having problems with this.

The baseurl in /etc/yum.repos.d/varnish.repo looks like this after the upgrade:

    baseurl=https://packagecloud.io/varnishcache/varnish41/el/7/

This gives me an error:

    https://packagecloud.io/varnishcache/varnish41/el/7/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

According to https://packagecloud.io/varnishcache/varnish41/install#manual-rpm it should be like this:

    baseurl=https://packagecloud.io/varnishcache/varnish41/el/7/$basearch

... and with that, things seems to work.
