### ISSUE TITLE
Missing syntax test in Rakefile

### ISSUE THREAD

**Issue by EmersonPrado** [maxchk/puppet-varnish#163]
Line 19 of [Rakefile](https://github.com/maxchk/puppet-varnish/blob/develop/Rakefile) reads:
`desc "Run syntax, lint, and spec tests."`
But the Rakefile specifies no syntax tests. We should add them.

**Comment by EmersonPrado** [comment]
Added [PR 164](https://github.com/maxchk/puppet-varnish/pull/164)

**Comment by luyseyal** [comment]
@EmersonPrado Does the merged PR close this issue?

**Comment by EmersonPrado** [comment]
@luyseyal It does.
