### ISSUE TITLE
Upgrade puppet forge version

### ISSUE THREAD

**Issue by pserrano** [maxchk/puppet-varnish#36]
Hi, 

Your module is very useful form make varnish servers, but it isn' t upgrade on pupperforge. Please, when you can, upgrade this for make better automatic servers :)

**Comment by malaikah** [comment]
Any thoughts? Need any help?

**Comment by pserrano** [comment]
Now i'm using better git submodules against puppet module install. Much better.

**Comment by prachetasp** [comment]
@pserrano Recommend closing?

**Comment by pserrano** [comment]
yeah, puppet forge is crap :D
