### ISSUE TITLE
Defining a varnish version to install doesn't work

### ISSUE THREAD

**Issue by solarnz** [maxchk/puppet-varnish#64]
When using this puppet module with this code

```
  class { 'varnish':
    version             => '4.0.3',
  }
```

Puppet is unable to install the correct varnish version on ubuntu trusty.

```
Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install varnish=4.0.3' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Version '4.0.3' for 'varnish' was not found

Error: /Stage[main]/Varnish::Install/Package[varnish]/ensure: change from purged to 4.0.3 failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install varnish=4.0.3' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Version '4.0.3' for 'varnish' was not found
```

However if I specify `4.0.3*` as the version number it works fine.

**Comment by KrisBuytaert** [comment]
Same problem on EL7  however 4.0.3.* won't work there..

**Comment by twardnw** [comment]
Adding my vote for this too, Ubuntu 14.04

**Comment by maverick72** [comment]
I've stripped the lookupvar varnish::params::version from the varnish-conf.erb and handling the versioning via a custon fact.  Also added some options i needed like thread_pools, thread_pool_add_delay, send_timeout and transient storage.  If anybody any of those i'll be happy to update my repo.
